import type { MenuItem } from "../../web/lib/types";

export const cardapioInicial: MenuItem[] = [
  { produto_id: "m1", name: "CHOOP PIL 500ML", price: 15, destino_producao: "bar", categoria: "Bebidas alcoólicas" },
  { produto_id: "m2", name: "SASSIONS IPA 500ML", price: 18, destino_producao: "bar", categoria: "Bebidas alcoólicas" },
  { produto_id: "m3", name: "CHOPP VINHO 500ML", price: 20, destino_producao: "bar", categoria: "Bebidas alcoólicas" },
  { produto_id: "m4", name: "COCA 350ML", price: 5.5, destino_producao: "bar", categoria: "Bebidas sem álcool" },
  { produto_id: "m5", name: "ÁGUA C GÁS", price: 3.5, destino_producao: "bar", categoria: "Bebidas sem álcool" },
  { produto_id: "m6", name: "CAIPIRINHA ART. DOSE", price: 6, destino_producao: "bar", categoria: "Bebidas alcoólicas" },
  { produto_id: "m7", name: "BATATA COM CHEDDAR E BACON", price: 28, destino_producao: "cozinha", categoria: "Porções" },
  { produto_id: "m8", name: "BATATA SIMPLES", price: 20, destino_producao: "cozinha", categoria: "Porções" },
  { produto_id: "m9", name: "PORÇ. TUL. TRAD", price: 20, destino_producao: "cozinha", categoria: "Porções" },
  { produto_id: "m10", name: "PORÇ. ALCATRA", price: 18, destino_producao: "cozinha", categoria: "Porções" },
  { produto_id: "m11", name: "HAMBÚRGUER COMPLETO", price: 45, destino_producao: "cozinha", categoria: "Lanche artesanal" },
  { produto_id: "m12", name: "PORÇÃO MISTA", price: 25, destino_producao: "cozinha", categoria: "Porções" },
  { produto_id: "real-american-300", name: "AMERICAN 300ML", price: 17, destino_producao: "bar", categoria: "Bebidas alcoólicas" },
  { produto_id: "real-american-500", name: "AMERICAN 500ML", price: 19, destino_producao: "bar", categoria: "Bebidas alcoólicas" },
  { produto_id: "real-cachaca", name: "CACHAÇA ART. DOSE", price: 6, destino_producao: "bar", categoria: "Bebidas alcoólicas" },
  { produto_id: "real-caipirinha", name: "CAIPIRINHA TRAD. LIM", price: 15, destino_producao: "bar", categoria: "Bebidas alcoólicas" },
  { produto_id: "real-choop-pil-300", name: "CHOOP PIL 300ML", price: 12, destino_producao: "bar", categoria: "Bebidas alcoólicas" },
  { produto_id: "real-chopp-vinho-300", name: "CHOPP VINHO 300ML", price: 18, destino_producao: "bar", categoria: "Bebidas alcoólicas" },
  { produto_id: "real-corona", name: "CORONA 330ML", price: 14, destino_producao: "bar", categoria: "Bebidas alcoólicas" },
  { produto_id: "real-heineken", name: "HEINEKEN 330ML", price: 12.5, destino_producao: "bar", categoria: "Bebidas alcoólicas" },
  { produto_id: "real-sassion-300", name: "SASSION IPA 300ML", price: 16, destino_producao: "bar", categoria: "Bebidas alcoólicas" },
  { produto_id: "real-stella", name: "STELLA 330ML", price: 13, destino_producao: "bar", categoria: "Bebidas alcoólicas" },
  { produto_id: "real-ultra", name: "ULTRA MICHELOB LONG", price: 12.5, destino_producao: "bar", categoria: "Bebidas alcoólicas" },
  { produto_id: "real-agua-limao", name: "ÁGUA C GÁS E LIMÃO", price: 4.5, destino_producao: "bar", categoria: "Bebidas sem álcool" },
  { produto_id: "real-aguas-gas", name: "ÁGUAS GÁS", price: 3, destino_producao: "bar", categoria: "Bebidas sem álcool" },
  { produto_id: "real-bud-zero", name: "BUDWEISER ZERO LONG", price: 12, destino_producao: "bar", categoria: "Bebidas sem álcool" },
  { produto_id: "real-fanta", name: "FANTA 350ML", price: 4.5, destino_producao: "bar", categoria: "Bebidas sem álcool" },
  { produto_id: "real-guarana", name: "GUARANÁ 350ML", price: 4.5, destino_producao: "bar", categoria: "Bebidas sem álcool" },
  { produto_id: "real-limao-gelo", name: "LIMÃO E GELO", price: 1.5, destino_producao: "bar", categoria: "Bebidas sem álcool" },
  { produto_id: "real-suco-laranja", name: "SUCO LARANJA 300ML", price: 4, destino_producao: "bar", categoria: "Bebidas sem álcool" },
  { produto_id: "real-tul-barb", name: "PORÇ. TUL. BARB.", price: 23, destino_producao: "cozinha", categoria: "Porções" },
  { produto_id: "real-tul-caram", name: "PORÇ. TUL. CARAM.", price: 25, destino_producao: "cozinha", categoria: "Porções" },
  { produto_id: "real-cab-lombo", name: "PORÇ. CAB. LOMBO", price: 13.5, destino_producao: "cozinha", categoria: "Porções" },
  { produto_id: "real-linguica", name: "PORÇ. LINGUIÇA TOSC.", price: 12, destino_producao: "cozinha", categoria: "Porções" },
  { produto_id: "real-panceta", name: "PORÇ. PANCETA", price: 15, destino_producao: "cozinha", categoria: "Porções" },
  { produto_id: "real-coracao", name: "PORÇÃO CORAÇÃO", price: 13, destino_producao: "cozinha", categoria: "Porções" },
  { produto_id: "real-batata-cheddar", name: "BATATA COM CHEDDAR", price: 24, destino_producao: "cozinha", categoria: "Porções" },
  { produto_id: "real-hamburguer-simples", name: "HAMBÚRGUER SIMPLES", price: 40, destino_producao: "cozinha", categoria: "Lanche artesanal" },
  { produto_id: "real-arroz", name: "ARROZ", price: 7, destino_producao: "cozinha", categoria: "Complementos" },
  { produto_id: "real-caldo", name: "CALDO DE FEIJÃO", price: 12, destino_producao: "cozinha", categoria: "Complementos" },
  { produto_id: "real-mandioca", name: "MANDIOCA", price: 5, destino_producao: "cozinha", categoria: "Complementos" },
  { produto_id: "real-vinagrete", name: "VINAGRETE", price: 7, destino_producao: "cozinha", categoria: "Complementos" },
  { produto_id: "real-monster", name: "ENER. MONSTER 473ML", price: 18, destino_producao: "bar", categoria: "Energético" },
];
